---
title: "Actividad Individual 7"
author: "Ángela Vieyto 5.487.839-8"
date: "Entrega 10/5/2021"
output:
  pdf_document: default
  html_document: default---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Esta actividad tiene que quedar disponible en su repositorio de GitHub con el resto de las actividades y tareas del curso. Asegurate que tanto Federico como yo seamos colaboradoras de tu proyecto Tareas_STAT_NT.
Recordar seleccionar en en opciones de proyecto, codificación de código UTF-8.

Para esta tarea deberás usar los datos de propinas disponibles en EVA.

# Ejercicio 1

1. Hacer un gráfico de dispersión: componentes estéticos `x` total, `y` propina, `color` fuma

2. Cambiá el nombre de los ejes: `x` = "Total gastado en dólares", `y` = "Propina en dólares"

3. Cambiá el nombre de la leyenda de `color` a "Fumador"

4. Cambiá la posición de la leyenda en la parte inferior del gráfico usando `theme`

5. Cambiar la paleta de colores a Dark2 usando `scale_color_brewer()`





# Ejercicio 2

1. Incluir un suavizado lineal usando `geom_smooth()`.

2. Cambiar el color de la linea a negro.


# Ejercicio 3

1. Hacer un gráfico de barras para la variable dia usando `geom_bar()`

2. Colorear por día de la semana las barras usar el elemento estético `fill`

3. Ordena los días según frecuencia (usá `fct_infreq()` de la librería `forcats`).


4. Rotá el gráfico usando `coord_flip()`.

